# Generated by Django 6.0.2 on 2026-04-18 16:36

import django.db.models.deletion
import layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayananKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_id', models.CharField(default=layanan.models.generate_kategori_id, editable=False, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layanan_id', models.CharField(default=layanan.models.generate_layanan_id, editable=False, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('durasi_menit', models.PositiveIntegerField(default=60, help_text='Durasi layanan dalam menit')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('harga', models.PositiveIntegerField(help_text='Harga layanan dalam rupiah')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layanans', to='layanan.layanankategori')),
            ],
            options={
                'ordering': ['kategori__nama', 'nama'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kategori', 'nama'), name='unique_active_layanan_per_kategori')],
            },
        ),
    ]
