# Generated by Django 6.0.2 on 2026-03-16 16:08

import django.db.models.deletion
import layanan.models
from django.db import migrations, models
from uuid import uuid4


def backfill_layanan_id(apps, schema_editor):
    Layanan = apps.get_model('layanan', 'Layanan')
    for layanan in Layanan.objects.filter(layanan_id__isnull=True).order_by('pk'):
        layanan.layanan_id = f"LYN-{uuid4().hex[:8].upper()}"
        layanan.save(update_fields=['layanan_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_id', models.CharField(default=layanan.models.generate_kategori_id, editable=False, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.AlterModelOptions(
            name='layanan',
            options={'ordering': ['kategori__nama', 'nama']},
        ),
        migrations.AddField(
            model_name='layanan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layanan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layanan',
            name='durasi_menit',
            field=models.PositiveIntegerField(default=60, help_text='Durasi layanan dalam menit'),
        ),
        migrations.AddField(
            model_name='layanan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layanan',
            name='layanan_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(backfill_layanan_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='layanan',
            name='layanan_id',
            field=models.CharField(default=layanan.models.generate_layanan_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='layanan',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layanans', to='layanan.layanankategori'),
        ),
        migrations.AddConstraint(
            model_name='layanan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kategori', 'nama'), name='unique_active_layanan_per_kategori'),
        ),
    ]
