# Generated by Django 6.0.2 on 2026-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_usage_per_unit_and_supply_assignment'),
        ('layanan', '0003_layanan_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayananSupplyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_per_use', models.PositiveIntegerField(help_text='Kuantitas pemakaian per 1 sesi layanan (harus > 0).')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan_configs', to='inventory.inventory')),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_configs', to='layanan.layanan')),
            ],
            options={
                'indexes': [models.Index(fields=['layanan', 'is_deleted'], name='layanan_lay_layanan_141a05_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('layanan', 'item'), name='unique_active_layanan_item_config')],
            },
        ),
    ]
