# Generated by Django 6.0.2 on 2026-04-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_layanan_is_active'),
        ('layanan', '0004_layanansupplyconfig'),
    ]

    operations = [
    ]
