# Generated by Django 6.0.2 on 2026-04-18 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('consultation_rate', models.PositiveIntegerField(default=0)),
                ('alamat', models.TextField(blank=True, default='', help_text='Therapist address')),
                ('no_hp', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('kota', models.CharField(blank=True, max_length=100, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked staff account for this therapist.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TherapistDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('override_type', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='therapist.therapist')),
            ],
            options={
                'ordering': ['therapist_id', 'date', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'date'], name='therapist_t_therapi_f876f1_idx'), models.Index(fields=['therapist', 'date', 'override_type'], name='therapist_t_therapi_bfd846_idx'), models.Index(fields=['is_active'], name='therapist_t_is_acti_41146b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TherapistWeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availabilities', to='therapist.therapist')),
            ],
            options={
                'ordering': ['therapist_id', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'day_of_week'], name='therapist_t_therapi_d378a0_idx'), models.Index(fields=['is_active'], name='therapist_t_is_acti_9df140_idx')],
            },
        ),
    ]
