# Generated by Django 6.0.2 on 2026-03-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_therapist_alamat_no_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='therapist.therapist')),
            ],
            options={
                'ordering': ['therapist_id', 'date', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'date'], name='therapist_t_therapi_f876f1_idx'), models.Index(fields=['therapist', 'date', 'is_available'], name='therapist_t_therapi_1d12b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TherapistWeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availabilities', to='therapist.therapist')),
            ],
            options={
                'ordering': ['therapist_id', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['therapist', 'day_of_week'], name='therapist_t_therapi_d378a0_idx'), models.Index(fields=['is_active'], name='therapist_t_is_acti_9df140_idx')],
            },
        ),
    ]
