# Generated by Django 6.0.2 on 2026-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_therapistdateoverride_therapistweeklyavailability'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='therapistdateoverride',
            name='therapist_t_therapi_1d12b4_idx',
        ),
        migrations.AddField(
            model_name='therapistdateoverride',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='therapistdateoverride',
            name='override_type',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='therapistdateoverride',
            index=models.Index(fields=['therapist', 'date', 'override_type'], name='therapist_t_therapi_bfd846_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistdateoverride',
            index=models.Index(fields=['is_active'], name='therapist_t_is_acti_41146b_idx'),
        ),
        migrations.RemoveField(
            model_name='therapistdateoverride',
            name='is_available',
        ),
    ]
