# Generated by Django 6.0.2 on 2026-03-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0004_therapist_address'),
        ('therapist', '0007_remove_therapistdateoverride_therapist_t_therapi_1d12b4_idx_and_more'),
    ]

    operations = [
    ]
