# Generated by Django 6.0.2 on 2026-03-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0010_alter_therapist_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='address',
        ),
    ]
