# Generated by Django 6.0.2 on 2026-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0011_remove_therapist_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
