# Generated by Django 6.0.2 on 2026-03-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Customer name', max_length=255)),
                ('alamat', models.TextField(help_text='Customer address')),
                ('kota', models.CharField(help_text='City', max_length=100)),
                ('no_hp', models.CharField(db_index=True, help_text='Phone number', max_length=20)),
                ('tgl_treatment', models.DateField(help_text='Treatment date')),
                ('jam_treatment', models.TimeField(help_text='Treatment time')),
                ('perawatan_pilihan', models.CharField(help_text='Selected treatment/service', max_length=255)),
                ('aromatherapy_oil', models.CharField(choices=[('JASMINE', 'Jasmine'), ('LAVENDER', 'Lavender'), ('ROSE', 'Rose'), ('SANDALWOOD', 'Sandalwood')], help_text='Selected aromatherapy oil', max_length=20)),
                ('kondisi_khusus', models.TextField(blank=True, help_text='Special conditions: Pregnant/Post-partum/Menstruation/Medical conditions')),
                ('tahu_dari', models.CharField(blank=True, help_text='How did you hear about Sènaira', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Booking status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional: linked user account for booking history', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tgl_treatment', '-jam_treatment'],
                'indexes': [models.Index(fields=['-tgl_treatment', '-jam_treatment'], name='booking_boo_tgl_tre_1980ee_idx'), models.Index(fields=['status'], name='booking_boo_status_e01616_idx')],
            },
        ),
    ]
