# Generated by Django 6.0.2 on 2026-04-18 16:36

import booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=booking.models.generate_booking_id, editable=False, help_text='6-digit alphanumeric booking ID', max_length=6, unique=True)),
                ('nama', models.CharField(help_text='Customer name', max_length=255)),
                ('alamat', models.TextField(help_text='Customer address')),
                ('kelurahan', models.CharField(blank=True, help_text='Kelurahan', max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, help_text='Kecamatan', max_length=100, null=True)),
                ('kota', models.CharField(help_text='City', max_length=100)),
                ('kode_pos', models.CharField(blank=True, help_text='Postal code', max_length=10)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude for booking location', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude for booking location', null=True)),
                ('no_hp', models.CharField(db_index=True, help_text='Phone number', max_length=20)),
                ('tgl_treatment', models.DateField(help_text='Treatment date')),
                ('jam_treatment', models.TimeField(help_text='Treatment time')),
                ('perawatan_pilihan', models.CharField(help_text='Selected treatment/service', max_length=255)),
                ('harga', models.DecimalField(blank=True, decimal_places=2, help_text='Base treatment price before shipping/adjustment', max_digits=12, null=True)),
                ('total_pembayaran', models.DecimalField(blank=True, decimal_places=2, help_text='Final payable amount including shipping/adjustment', max_digits=12, null=True)),
                ('aromatherapy_oil', models.CharField(choices=[('JASMINE', 'Jasmine'), ('LAVENDER', 'Lavender'), ('ROSE', 'Rose'), ('SANDALWOOD', 'Sandalwood')], help_text='Selected aromatherapy oil', max_length=20)),
                ('kondisi_khusus', models.TextField(blank=True, help_text='Special conditions: Pregnant/Post-partum/Menstruation/Medical conditions')),
                ('tahu_dari', models.CharField(blank=True, help_text='How did you hear about Sènaira', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (visible to staff only)')),
                ('cancellation_reason', models.TextField(blank=True, default='', help_text='Reason required when booking is cancelled')),
                ('voucher_code', models.CharField(blank=True, help_text='Applied voucher code for this booking', max_length=100)),
                ('review_token', models.CharField(blank=True, db_index=True, help_text='Secure token used in QR link for customer review', max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Booking status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(blank=True, help_text='Assigned therapist for this booking', limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Optional: linked user account for booking history', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tgl_treatment', '-jam_treatment'],
            },
        ),
        migrations.CreateModel(
            name='BookingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='booking_boo_booking_fd5f41_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-tgl_treatment', '-jam_treatment'], name='booking_boo_tgl_tre_1980ee_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingchangelog',
            index=models.Index(fields=['booking', '-changed_at'], name='booking_boo_booking_8e1e16_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingchangelog',
            index=models.Index(fields=['field_name'], name='booking_boo_field_n_ca8c69_idx'),
        ),
    ]
