# Generated by Django 6.0.2 on 2026-03-09 14:51

import booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=booking.models.generate_booking_id, editable=False, help_text='6-digit alphanumeric booking ID', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (visible to staff only)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(blank=True, help_text='Assigned therapist for this booking', limit_choices_to={'role': 'THERAPIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='booking_boo_booking_fd5f41_idx'),
        ),
    ]
