# Generated by Django 6.0.2 on 2026-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token used in QR link for customer review', max_length=128, null=True, unique=True),
        ),
    ]
