# Generated by Django 6.0.2 on 2026-03-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_geolocation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Booking status', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='booking.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['booking', '-changed_at'], name='booking_boo_booking_8e1e16_idx'), models.Index(fields=['field_name'], name='booking_boo_field_n_ca8c69_idx')],
            },
        ),
    ]
