# Generated by Django 6.0.2 on 2026-03-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_review_token'),
        ('booking', '0006_booking_kode_pos'),
    ]

    operations = [
    ]
