# Generated by Django 6.0.2 on 2026-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_merge_0004_booking_review_token_0006_booking_kode_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base treatment price before shipping/adjustment', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_pembayaran',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final payable amount including shipping/adjustment', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Booking status', max_length=20),
        ),
    ]
