# Generated by Django 6.0.2 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_harga_booking_total_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason required when booking is cancelled'),
        ),
    ]
