# Generated by Django 6.0.2 on 2026-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_cancellation_reason'),
        ('layanan', '0004_layanansupplyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='layanans',
            field=models.ManyToManyField(blank=True, help_text='Mapped treatments/services (Many-to-Many)', related_name='bookings', to='layanan.layanan'),
        ),
    ]
