# Generated by Django 6.0.2 on 2026-04-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_cancellation_reason'),
        ('booking', '0010_booking_layanans'),
    ]

    operations = [
    ]
