# Generated by Django 6.0.2 on 2026-04-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_promo_layanan_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='layanan',
        ),
    ]
