# Generated by Django 6.0.2 on 2026-04-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_promo_layanan'),
        ('layanan', '0004_layanansupplyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, help_text='Layanan yang berlaku untuk promo ini. Kosong = semua layanan', related_name='applicable_promos', to='layanan.layanan'),
        ),
        migrations.AddField(
            model_name='promo',
            name='benefit_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potongan harga dalam Rp jika benefit_type adalah discount_nominal', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='benefit_discount_percent',
            field=models.IntegerField(blank=True, help_text='Potongan harga dalam % jika benefit_type adalah discount_percent', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='benefit_free_service',
            field=models.ForeignKey(blank=True, help_text='Layanan gratis jika benefit_type adalah free_service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_service_promos', to='layanan.layanan'),
        ),
        migrations.AddField(
            model_name='promo',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('free_service', 'Gratis Layanan'), ('discount_nominal', 'Potongan Rp'), ('discount_percent', 'Potongan %')], help_text='Tipe benefit promo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum total harga layanan untuk berlaku promo (dalam Rp)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='show_in_booking',
            field=models.BooleanField(default=True, help_text='Tampilkan promo ini di halaman booking customer'),
        ),
    ]
