# Generated by Django 6.0.2 on 2026-04-18 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('Sticker', 'Sticker'), ('Bahan Body Massage', 'Bahan Body Massage'), ('Bahan Scrub', 'Bahan Scrub'), ('Bahan Masker', 'Bahan Masker'), ('Bahan Creambath', 'Bahan Creambath'), ('Bahan Totok Wajah & Natural Facial', 'Bahan Totok Wajah & Natural Facial'), ('Bahan Foot Reflexy', 'Bahan Foot Reflexy'), ('Bahan Lainnya', 'Bahan Lainnya'), ('Alat-Alat Perawatan', 'Alat-Alat Perawatan'), ('Seragam Batik', 'Seragam Batik'), ('Keterangan Tambahan', 'Keterangan Tambahan')], max_length=80)),
                ('lokasi', models.CharField(choices=[('CILEGON', 'CILEGON'), ('SERANG', 'SERANG'), ('BATAM', 'BATAM')], default='CILEGON', max_length=20)),
                ('jumlah_stok', models.PositiveIntegerField()),
                ('threshold_minimum', models.PositiveIntegerField()),
                ('usage_per_unit', models.PositiveIntegerField(default=1, help_text='Kapasitas penggunaan per 1 unit item (harus > 0).')),
                ('keterangan', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'ordering': ['nama_barang'],
            },
        ),
        migrations.CreateModel(
            name='TherapistSupplyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField(help_text='Berapa unit item yang dibawa therapist.')),
                ('usage_per_unit', models.PositiveIntegerField(help_text='Snapshot usagePerUnit dari inventory saat assignment dibuat.')),
                ('total_usage', models.PositiveIntegerField(help_text='quantityAssigned * usagePerUnit (dihitung otomatis).')),
                ('remaining_usage', models.PositiveIntegerField(help_text='Sisa kapasitas penggunaan.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(help_text='User yang membuat assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User yang menghapus assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Item inventory yang di-assign.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='inventory.inventory')),
                ('therapist', models.ForeignKey(help_text='Therapist yang menerima assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='therapist.therapist')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User yang terakhir mengubah assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'therapist supply assignment',
                'verbose_name_plural': 'therapist supply assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['item', 'therapist'], name='inventory_t_item_id_0ab21c_idx'), models.Index(fields=['therapist', 'status'], name='inventory_t_therapi_ac72cc_idx'), models.Index(fields=['status'], name='inventory_t_status_306374_idx')],
            },
        ),
    ]
