# Generated by Django 6.0.2 on 2026-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah_stok', models.PositiveIntegerField()),
                ('threshold_minimum', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'ordering': ['nama_barang'],
            },
        ),
    ]
