# Generated by Django 6.0.2 on 2026-04-10 15:05

from django.db import migrations, models

_VALID_KATEGORI = frozenset(
    {
        "Sticker",
        "Bahan Body Massage",
        "Bahan Scrub",
        "Bahan Masker",
        "Bahan Creambath",
        "Bahan Totok Wajah & Natural Facial",
        "Bahan Foot Reflexy",
        "Bahan Lainnya",
        "Alat-Alat Perawatan",
        "Seragam Batik",
        "Keterangan Tambahan",
    }
)


def _normalize_kategori(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")
    fallback = "Bahan Lainnya"
    for row in Inventory.objects.all():
        if row.kategori not in _VALID_KATEGORI:
            row.kategori = fallback
            row.save(update_fields=["kategori"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='keterangan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lokasi',
            field=models.CharField(choices=[('CILEGON', 'CILEGON'), ('SERANG', 'SERANG'), ('BATAM', 'BATAM')], default='CILEGON', max_length=20),
        ),
        migrations.RunPython(_normalize_kategori, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventory',
            name='kategori',
            field=models.CharField(choices=[('Sticker', 'Sticker'), ('Bahan Body Massage', 'Bahan Body Massage'), ('Bahan Scrub', 'Bahan Scrub'), ('Bahan Masker', 'Bahan Masker'), ('Bahan Creambath', 'Bahan Creambath'), ('Bahan Totok Wajah & Natural Facial', 'Bahan Totok Wajah & Natural Facial'), ('Bahan Foot Reflexy', 'Bahan Foot Reflexy'), ('Bahan Lainnya', 'Bahan Lainnya'), ('Alat-Alat Perawatan', 'Alat-Alat Perawatan'), ('Seragam Batik', 'Seragam Batik'), ('Keterangan Tambahan', 'Keterangan Tambahan')], max_length=80),
        ),
    ]
