# Generated by Django 6.0.2 on 2026-04-13 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_kategori_lokasi'),
        ('therapist', '0013_merge_address_into_alamat_and_remove_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='usage_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='Kapasitas penggunaan per 1 unit item (harus > 0).'),
        ),
        migrations.CreateModel(
            name='TherapistSupplyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField(help_text='Berapa unit item yang dibawa therapist.')),
                ('usage_per_unit', models.PositiveIntegerField(help_text='Snapshot usagePerUnit dari inventory saat assignment dibuat.')),
                ('total_usage', models.PositiveIntegerField(help_text='quantityAssigned * usagePerUnit (dihitung otomatis).')),
                ('remaining_usage', models.PositiveIntegerField(help_text='Sisa kapasitas penggunaan.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(help_text='User yang membuat assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User yang menghapus assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_deleted', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Item inventory yang di-assign.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='inventory.inventory')),
                ('therapist', models.ForeignKey(help_text='Therapist yang menerima assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_assignments', to='therapist.therapist')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User yang terakhir mengubah assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'therapist supply assignment',
                'verbose_name_plural': 'therapist supply assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['item', 'therapist'], name='inventory_t_item_id_0ab21c_idx'), models.Index(fields=['therapist', 'status'], name='inventory_t_therapi_ac72cc_idx'), models.Index(fields=['status'], name='inventory_t_status_306374_idx')],
            },
        ),
    ]
