# Generated by Django 6.0.2 on 2026-04-16 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_layanans'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(help_text='Kuantitas penggunaan item.')),
                ('tanggal', models.DateField(help_text='Tanggal pemakaian (biasanya tanggal booking treatment).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking terkait untuk jejak audit/idempotensi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_usage_logs', to='booking.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='inventory.inventory')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'THERAPIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='supply_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'supply usage logs',
                'ordering': ['-tanggal', '-created_at'],
                'indexes': [models.Index(fields=['item', 'therapist', 'tanggal'], name='inventory_s_item_id_bca7e8_idx'), models.Index(fields=['tanggal'], name='inventory_s_tanggal_8053c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'item', 'therapist'), name='unique_booking_item_therapist_usage_log')],
            },
        ),
    ]
