# Generated by Django 6.0.2 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_supplyusagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="assignment_inactive_after_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text=(
                    "Batas hari dasar sebelum assignment dianggap INACTIVE. "
                    "Masa aktif efektif assignment = nilai ini x quantity_assigned."
                ),
            ),
        ),
    ]
