# Generated by Django 6.0.2 on 2026-04-18 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplyusagelog'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyusagelog',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_usage_logs', to='therapist.therapist'),
        ),
    ]
