# Generated by Django 6.0.2 on 2026-04-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_supplyusagelog_therapist'),
        ('inventory', '0005_inventory_assignment_inactive_after_days'),
    ]

    operations = [
    ]
