# Generated by Django 6.0.2 on 2026-03-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(default='', help_text='Customer display name captured from booking data.', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_phone',
            field=models.CharField(db_index=True, default='', help_text='Customer phone number captured from booking data.', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer who wrote the review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
